# generated by datamodel-codegen:
#   filename:  challenge_set.schema.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, RootModel, conint, constr


class Era(Enum):
    """
    Historical era / civilization theme of the map.
    """

    greek_colonies = "greek_colonies"
    phoenician_carthaginian = "phoenician_carthaginian"
    roman_hispania = "roman_hispania"
    visigothic = "visigothic"
    al_andalus = "al_andalus"
    christian_kingdoms = "christian_kingdoms"


class Answer(RootModel[constr(min_length=1)]):
    root: constr(min_length=1)


class Language(Enum):
    es = "es"
    en = "en"


class Subject(Enum):
    math = "math"
    spanish = "spanish"
    science_en = "science_en"
    history = "history"
    geography = "geography"
    english = "english"
    electronics = "electronics"


class LocalizedText(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    text: constr(min_length=1)
    language: Language


class Reward(BaseModel):
    """
    Resource reward granted on success (fheroes2 Funds).
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    gold: conint(ge=0) | None = 0
    wood: conint(ge=0) | None = 0
    ore: conint(ge=0) | None = 0
    mercury: conint(ge=0) | None = 0
    sulfur: conint(ge=0) | None = 0
    crystal: conint(ge=0) | None = 0
    gems: conint(ge=0) | None = 0


class Sphinx(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    subject: Subject
    concept_tags: list[str] = Field(..., min_length=1)
    riddle: LocalizedText
    answers: list[Answer] = Field(
        ...,
        description="All accepted answer strings. fheroes2 matches EXACTLY, so enumerate tolerant variants (case, accents, synonyms, es/en).",
        min_length=1,
    )
    hint: LocalizedText | None = None
    reward: Reward


class Event(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    message: LocalizedText
    reward: Reward


class ChallengeSet(BaseModel):
    """
    The educational layer the AI authors for one day's map and learner: curriculum-tagged Sphinx riddles, signs and events to be patched into a fheroes2 .fh2m template. The strict contract for the local LLM (Ollama structured output) and validated server-side.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["1"]
    profile_id: constr(pattern=r"^[a-z][a-z0-9_]*$")
    era: Era = Field(..., description="Historical era / civilization theme of the map.")
    language_default: Language
    sphinxes: list[Sphinx] = Field(
        ...,
        description="Riddle challenges, one per Sphinx slot in the template.",
        min_length=1,
    )
    signs: list[LocalizedText] | None = Field(
        None, description="Lore / hint text placed on signs."
    )
    events: list[Event] | None = Field(
        None, description="Adventure-map events: a message plus a reward."
    )
