# generated by datamodel-codegen:
#   filename:  curriculum.schema.json

from __future__ import annotations

from enum import Enum

from pydantic import BaseModel, ConfigDict, Field, confloat, conint, constr


class Subject1(Enum):
    math = "math"
    spanish = "spanish"
    science_en = "science_en"
    history = "history"
    geography = "geography"
    english = "english"
    electronics = "electronics"


class Language(Enum):
    """
    Language puzzles for this subject must be presented in.
    """

    es = "es"
    en = "en"


class Concept(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    concept_id: constr(pattern=r"^[a-z][a-z0-9_]*$")
    label: str
    difficulty: conint(ge=1, le=5)


class Subject(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    subject: Subject1
    language: Language = Field(
        ..., description="Language puzzles for this subject must be presented in."
    )
    weight: confloat(ge=0.0) | None = Field(
        1, description="Relative emphasis when generating the daily level."
    )
    concepts: list[Concept] = Field(..., min_length=1)


class Curriculum(BaseModel):
    """
    Data-driven pedagogy binding a profile to subjects and concepts. Adding a profile is adding one of these.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    curriculum_ref: constr(pattern=r"^[a-z][a-z0-9_]*$")
    title: str | None = None
    subjects: list[Subject] = Field(..., min_length=1)
