# generated by datamodel-codegen:
#   filename:  daily_level.schema.json

from __future__ import annotations

from enum import Enum
from typing import Literal

from pydantic import BaseModel, ConfigDict, Field, conint, constr


class Kind(Enum):
    grass = "grass"
    water = "water"
    mountain = "mountain"
    wall = "wall"
    road = "road"
    forest = "forest"
    sand = "sand"


class TileLegend(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    name: str
    walkable: bool
    kind: Kind


class Type(Enum):
    chest = "chest"
    npc = "npc"
    monster = "monster"


class Kind1(Enum):
    multiple_choice = "multiple_choice"
    free_text = "free_text"
    i_spy_shape = "i_spy_shape"
    name_in_english = "name_in_english"
    circuit = "circuit"


class Team(Enum):
    player = "player"
    enemy = "enemy"


class Stats(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    hp: conint(ge=1)
    atk: conint(ge=0)
    def_: conint(ge=0) = Field(..., alias="def")
    speed: conint(ge=0)
    range: conint(ge=1)


class Language(Enum):
    es = "es"
    en = "en"


class Subject(Enum):
    math = "math"
    spanish = "spanish"
    science_en = "science_en"
    history = "history"
    geography = "geography"
    english = "english"
    electronics = "electronics"


class GridPos(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    x: conint(ge=0)
    y: conint(ge=0)


class AxialCoord(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    q: int
    r: int


class LocalizedText(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    text: str
    language: Language


class Overworld(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    width: conint(ge=1, le=64)
    height: conint(ge=1, le=64)
    tile_legend: dict[str, TileLegend] = Field(
        ...,
        description="Map from stringified integer tile id to its definition.",
        min_length=1,
    )
    matrix: list[list[conint(ge=0)]] = Field(
        ..., description="height rows of width tile ids; ids must exist in tile_legend."
    )
    start: GridPos


class Entity(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    type: Type
    pos: GridPos
    puzzle_ref: str | None = None
    dialogue_ref: str | None = None
    encounter_ref: str | None = None
    lore: str | None = Field(
        None, description="Lore tag, e.g. 'gamusino', 'cuelebre', 'artificer_device'."
    )


class Puzzle(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    concept_tags: list[str] = Field(..., min_length=1)
    subject: Subject
    prompt: LocalizedText
    kind: Kind1
    options: list[str] | None = None
    answer: str = Field(..., description="Canonical answer.")
    accepted_answers: list[str] | None = Field(
        None, description="Additional accepted forms (normalized client-side)."
    )
    hint: LocalizedText | None = None


class Line(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    text: str
    language: Language
    voice: str = Field(..., description="Piper voice id mapped server-side.")


class Dialogue(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    speaker: str
    lines: list[Line] = Field(..., min_length=1)


class Unit(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    team: Team
    name: str
    axial: AxialCoord
    initiative: conint(ge=0)
    stats: Stats
    lore: str | None = None


class Encounter(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    id: str
    hex_radius: conint(ge=1, le=8)
    units: list[Unit] = Field(..., min_length=2)


class DailyLevel(BaseModel):
    """
    The strict contract the local LLM must return for one day's level. Cross-field invariants (matrix dims, ref resolution, axial-in-radius, >=1 player unit) are enforced by schema_validator.py and the client LevelLoader.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    schema_version: Literal["1"]
    profile_id: constr(pattern=r"^[a-z][a-z0-9_]*$")
    language_default: Language
    overworld: Overworld
    entities: list[Entity]
    puzzles: list[Puzzle]
    dialogues: list[Dialogue]
    encounters: list[Encounter]
