# generated by datamodel-codegen:
#   filename:  player_profile.schema.json

from __future__ import annotations

from datetime import date as date_aliased
from enum import Enum

from pydantic import (
    AwareDatetime,
    BaseModel,
    ConfigDict,
    Field,
    confloat,
    conint,
    constr,
)


class Result(Enum):
    cleared = "cleared"
    defeated = "defeated"


class HistoryItem(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    date: date_aliased
    result: Result
    hp_pct: confloat(ge=0.0, le=1.0)


class Subject(Enum):
    math = "math"
    spanish = "spanish"
    science = "science"
    history = "history"
    geography = "geography"
    english = "english"
    electronics = "electronics"


class ReinforceConcept(BaseModel):
    model_config = ConfigDict(
        extra="forbid",
    )
    concept_id: str
    subject: Subject
    failures: conint(ge=1)
    added_at: AwareDatetime | None = None


class PlayerProfile(BaseModel):
    """
    Per-player learning and progress profile. Real instances are private (gitignored); only generic examples are committed.
    """

    model_config = ConfigDict(
        extra="forbid",
    )
    profile_id: constr(pattern=r"^[a-z][a-z0-9_]*$") = Field(
        ..., description="Stable key, e.g. 'youth_10yo'. Binds to a curriculum."
    )
    display_name: str | None = Field(
        None,
        description="Human name. Present only in private live profiles, never in committed examples.",
    )
    age: conint(ge=3, le=120)
    curriculum_ref: constr(pattern=r"^[a-z][a-z0-9_]*$") = Field(
        ...,
        description="Curriculum file id under curricula/profiles, e.g. 'youth_10yo'.",
    )
    difficulty_modifier: confloat(ge=0.1) = Field(
        ...,
        description="Global difficulty multiplier. 1.0 = baseline; ×1.10 on strong clears.",
    )
    defeat_streak: conint(ge=0) = Field(
        ..., description="Consecutive defeats; >= 2 triggers anti-frustration."
    )
    last_level_started_at: AwareDatetime | None = Field(
        None,
        description="ISO-8601 timestamp when the current level started, for the time-over-limit trigger.",
    )
    reinforce_concepts: list[ReinforceConcept] | None = Field(
        None, description="Concepts the player failed and should be re-taught next."
    )
    mastered_concepts: list[str] | None = None
    history: list[HistoryItem] | None = None
